// Labels em português para as chaves de especificações técnicas (especificacoes JSON)
export const SPEC_LABELS: Record<string, string> = {
  tipo: "Tipo", resolucao: "Resolução", resolucao_maxima: "Resolução máxima",
  iluminacao: "Iluminação", alcance_ir: "Alcance IR", angulo_visao: "Ângulo de visão",
  sensor: "Sensor", fps: "Taxa de imagem", compressao: "Compressão",
  lente: "Lente", protecao_ip: "Protecção IP", protecao_ik: "Protecção IK",
  poe: "PoE", wifi: "Wi-Fi", bluetooth: "Bluetooth", audio: "Áudio",
  armazenamento_interno: "Armazenamento interno", armazenamento: "Armazenamento",
  comunicacao: "Comunicação", alimentacao: "Alimentação", temperatura: "Temp. funcionamento",
  humidade: "Humidade", grau_protecao: "Grau de protecção", grau_seguranca: "Grau de segurança",
  dimensoes: "Dimensões", peso: "Peso", cor: "Cor", canais: "Canais",
  tecnologia: "Tecnologia", bateria: "Bateria", ia: "Inteligência Artificial",
  wdr: "WDR / HDR", protocolo: "Protocolo", interface_rede: "Interface de rede",
  encriptacao: "Encriptação", firmware_ota: "Firmware OTA", frequencia: "Frequência",
  distancia_transmissao: "Distância de transmissão", compatibilidade: "Compatibilidade",
  funcoes_inteligentes: "Funções inteligentes", acesso_remoto: "Acesso remoto",
  alarme: "Alarme", sensibilidade: "Sensibilidade", gama: "Gama",
  processador: "Processador", geracao: "Geração", grafica: "Placa Gráfica",
  ram_gb: "RAM (GB)", ram_tipo: "Tipo de RAM", ram_slots: "Slots RAM",
  ram_ampliavel: "RAM Ampliável", armazenamento_gb: "Armazenamento (GB)",
  armazenamento_tipo: "Tipo de armazenamento", ecra_polegadas: "Ecrã (\")",
  sistema_operativo: "Sistema Operativo", grau: "Grau", teclado: "Teclado",
  leitor_gravador: "Leitor/Gravador", webcam: "Webcam",
  portas: "Portas", portas_frontais: "Portas frontais", portas_traseiras: "Portas traseiras", instalacao: "Instalação",

  // Novos campos Visiotech v3
  protecao_corrosao: "Protecção anti-corrosão", captacao_facial: "Captação facial",
  detecao_movimento: "Detecção de movimento", ajuste_3_eixos: "Ajuste 3 eixos",
  zoom_ptz: "Zoom óptico PTZ", resolucao_max_gravacao: "Resolução máx. gravação",
  capacidade_gravacao: "Capacidade de gravação", tipo_camara: "Tipo de câmara",
  tipo_detecao: "Tipo de detecção", audio_io: "Entradas/Saídas áudio",
  microfone_altavoz: "Microfone/Altifalante", baias_hdd: "Baías HDD",
  movimento_remoto: "Movimento remoto",
  portas_totais: "Nº portas totais", velocidade_uplink: "Velocidade uplink",
  velocidade_lan: "Velocidade portas LAN", portas_poe: "Portas PoE",
  poe_total: "PoE total", entradas_poe: "Entradas PoE",
  comunicacao_sem_fios: "Comunicação sem fios", comunicacao_principal: "Comunicação principal",
  requer_gateway: "Requer Gateway/Hub",
  categoria_cabo: "Categoria do cabo", comprimento: "Comprimento",
  tipo_cabo: "Tipo de cabo", tipo_condutor: "Tipo de condutor",
  blindagem: "Blindagem", modo_corredor: "Modo corredor",
  alimentacao_poc: "Alimentação PoC", potencia: "Potência", tensao_saida: "Tensão de saída",
  capacidade: "Capacidade",
  tipo_montagem: "Tipo de montagem", ambiente: "Ambiente",
  cenario_instalacao: "Cenário de instalação", grau_resistencia: "Grau de resistência",
  tecnologia_rfid: "Tecnologia RFID",
  tipo_painel: "Tipo de Painel", vesa: "Suporte VESA",
  profundidade_de_cinzentos: "Profundidade de cinzentos", profundidade_de_colores: "Profundidade de cores",
  ecra: "Ecrã", modelo: "Modelo", otras_funciones: "Outras funções",
};
